services:
  postgres:
    image: postgres:15.3-alpine
    ports:
      - ${DATABASE_PORT}:5432
    volumes:
      - ./.data/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  shadow-postgres:
    image: postgres:15.3-alpine
    ports:
      - ${SHADOW_DATABASE_PORT}:5432
    volumes:
      - ./.data/shadow-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${SHADOW_DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${SHADOW_DATABASE_PASSWORD}
      POSTGRES_DB: ${SHADOW_DATABASE_NAME}

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${APP_PORT}:${APP_PORT}
